deploy:
  provider: pypi
  username: __token__
  password:
    secure: Q4nYLvPQI89qc04JPgVqlHuXji5jdnXG9IXC6bFS0PgSNu2h3y08rAg5yKgXE9bWPpbrn5Z+cmBixpOO3xW9KeKx3CVwdVbFcPAJ2LI6sapjV2FwQx8iGb2TpR3ZZUCImE5Vk85IzMLr2Cd3jogngwM2YcwGi2CCyV/cf/JBUivTJDGhIm5UQakN/WtrPsS2/cL11m5t6XmsdXLTG1BAlUDrLySh36HSY4mRxpsgYOqhhJenzZuyHUkDGbFPohaPrXsbr4QgPRB4sB8JJGuXFE6BnVqE3Ke+Bk8w5TTOePZHbcB7NUXGCYMEyxo6Zpxxg89KxqvsQu450cE+vdz9Hu1VG5xoDB7G8sdEFw36dLJCOIyVYKNnLk86v9cFk+gu1uN7wsygNu6rp6whzK1LHhyfC43Nxqg/0JtTVUn+0vOd/87/lKXokIvoGV5PcSdiYkmCfLUSxXsG7WzrkZJ3chU1vHTrF5Evgr9KS+0VAXvanzorUo8dU258TKG3won7kFfDogrDUPpUZjMKPS5YtRwc2JK6MvGgpCGpe4NEnCAJELEWMmccx3JogPk+EDSsqK1Q+7XV47KbRFcye67mp+60C416nkBmB7irzJj2w1ASp1wIh7yASP3DDfo08T9v+IGymYAz9uc28HCx+QY5TsEyI+TmGALyMAjrHqdDMEc=
  on:
    tags: true
    branch: main
