language: python
python:
- '3.8'
services:
- redis
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: EkU3mQJpIn7TrJKw9YElCPatygqgc1GCqDETU6T/zvh85GYqZ0BihKOvzuTu5D7n+Ka7a/F2WxIOXc1Npi1c7wx6XvtJ1lcQi+kkpuzdlkXfI0b5s1qkKbwcvL6csEQ0XZXxMSqjzgG13jhpB+yOvDoKgMCs4u2Ia+it1DE3fiNyIvO2XZZr0O6yykHXzeaYnQQ3aDLJWeDRGs1idsJdIqwVi3nB8A80xwchsdzDAFQ/faQkKIy6rJ+b/EwyvweHuO386J2DP4Y1HAPzoCCQFszH919+crw46mM0KdFsDQBEf8Exph4DX9YBv1Neo/yiyUQw9HM49FkXzlXXlRq3YbrK0elVNnZbhu08VsYDDuW3U0PnD0WH8uK7x3L8aFFonl0gz/up5fi94dTqPXhc19sUfxX7RZFhdgxLwZwMaaSVRBztkH+J7VXoRs1iKZ9Nn9nUVF/mF64q6HsfFoqXsSHoByZWgHqb2gabVYtTAbvt8QOTcdk80oQ+Gl4Q2QDJxPSJ15WAJ6UuUA632XB0/e8htABSadY2mFGp4tWNP0ePpo3u6793OgWFRE60EAyy46ZFSz01iz9m5SV7/c/3IzvSNt7dujrj78nQOcQkcK+Xye0GtlXhM/+IM8cLMxutsPZTDlhBAy6TLOY1uqbV8rlUQNJHnpWpt5sk+d360DY=
  on:
    tags: true
    branch: main
