language: python
python:
- '3.8'
services:
- redis
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: "PcRe/YbutId1Xc5SV9WCuGMbuRqyCFKyaRIU+vkYV0EETZBPP9y/DxiZC8/k+no6BOn51Y661IVvph6/qwavis1emphdVWCTzBjMFoWagPSHVodiXEch2VQeCLQKQlxzrdcNfpk6yICKbelAo4dz3/vWSJJclPUUpY5NpPGXl+0HUDadXBqxn+m9baX0kN1/I6lZYpR3ucdUWpPHkKet/3c7BWwv9QbZn/6ERAnQNzJFrIonqSviz4WAhWpRybI1dpJV4FO41lOIjNWT1hsDmmWbPlWQD2fDtjm9t/PI1jmkEcHl4q7PrFJXK8WmIZ0re5UqIfLYJDRFPKXtCVREv+gdEyY20H2l/zekXo6aDFHMZewgwKHvmd3kpQBB70tX6j45cOYPAvRcPcBX3gkWtuxFSzSisZBcdYyP6JGbe8B6XAWDt8Eh45SxNT74cuNzA4T0bgGMrYh7YPscXR7Q/u4ylTJxDDjoyXQf1fxt+weyWhbMBjbfsmSCyr79TS/hrWyLiOUPykdDxD8lnfFdz9LAR/NEIklFU/oIgoC/2pI7X2EgthKpS5sbPkxU3p4b6CJHpWTK1qwV7FJwNdxeg8PkR7dfeyrJWj6dkixCPxDUevTj7NrW2vNR9b5W6NRdpZUc6/kSMQ9buc6KT03PT8tDLM1g4j7yvLYY9w2IQvk="
  on:
    tags: true
    branch: main
